import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import {
  buildMaterialCatalogGroups,
  cleanMaterialName,
  getMaterialCategoryOptions,
  getMaterialDisplayName,
  getMaterialGroupInventoryMaterial,
  getMaterialTypeOptions,
} from "../src/utils/dentalMaterialCatalog.js";

const INPUT_JSON = resolve("data/dental_materials.seed.json");
const OUTPUT_JS = resolve("src/data/dentalMaterialCatalogPrepared.js");
const OUTPUT_DIR = dirname(OUTPUT_JS);
const MATERIAL_CHUNK_PREFIX = "dentalMaterialCatalogPrepared.materials";
const GROUP_CHUNK_PREFIX = "dentalMaterialCatalogPrepared.groups";
const CHUNK_COUNT = 4;

function hashText(value) {
  let hash = 5381;
  for (const char of String(value || "")) {
    hash = ((hash << 5) + hash) ^ char.codePointAt(0);
  }
  return (hash >>> 0).toString(36);
}

function compactMaterial(material, group, variant, materialId) {
  const inventoryMaterial = getMaterialGroupInventoryMaterial(group, variant.key);

  return {
    catalog_id: materialId,
    source_catalog_id: material.catalog_id,
    name: inventoryMaterial.name,
    display_name: getMaterialDisplayName(material),
    app_display_name: inventoryMaterial.name,
    representative_name: group.representativeName,
    variant_label: variant.label,
    category: material.category,
    category_id: material.category_id,
    source_category: material.source_category,
    unit: material.unit,
    spec: material.spec || "",
    manufacturer: material.manufacturer || "",
    min_order_qty: material.min_order_qty || 1,
    expiry_managed: Boolean(material.expiry_managed),
    vendor_options: Array.isArray(material.vendor_options) ? material.vendor_options : [],
  };
}

function compactGroup(group, materialById) {
  const variantsWithMaterials = group.variants.map(variant => {
    const materialId = `pm_${hashText(variant.key)}`;
    const material = compactMaterial(variant.material, group, variant, materialId);
    materialById.set(material.catalog_id, material);
    return {
      key: variant.key,
      label: variant.label,
      vendorCount: variant.vendorCount,
      material_id: material.catalog_id,
      material,
    };
  });

  return {
    key: group.key,
    representativeName: group.representativeName,
    category: group.category,
    type: group.type,
    unit: group.unit,
    manufacturer: group.manufacturer || "",
    vendorCount: group.vendorCount,
    variantCount: variantsWithMaterials.length,
    variants: variantsWithMaterials.map(({ material: _material, ...variant }) => variant),
  };
}

function countOptions(groups, getValue) {
  const counts = groups.reduce((acc, group) => {
    const value = getValue(group);
    if (!value) return acc;
    acc.set(value, (acc.get(value) || 0) + 1);
    return acc;
  }, new Map());

  return [...counts.entries()]
    .map(([value, count]) => ({ value, label: value, count }))
    .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label, "ko-KR"));
}

function buildTypeOptionsByCategory(groups) {
  return groups.reduce((acc, group) => {
    if (!acc[group.category]) acc[group.category] = [];
    return acc;
  }, {});
}

function stableJson(value) {
  return JSON.stringify(value, null, 2);
}

function chunkEvenly(items, chunkCount = CHUNK_COUNT) {
  const chunkSize = Math.ceil(items.length / chunkCount);
  return Array.from({ length: chunkCount }, (_, index) =>
    items.slice(index * chunkSize, (index + 1) * chunkSize)
  ).filter(chunk => chunk.length > 0);
}

function chunkHeader() {
  return `// DentalStock prepared material catalog.
// Generated by scripts/generateDentalMaterialCatalog.mjs from data/dental_materials.seed.json.
// Split into lazy chunks so the app shell does not bundle the full catalog.
// Do not edit manually.

`;
}

function buildChunkLoaderLines(prefix, chunks) {
  return chunks
    .map((_chunk, index) => `  () => import("./${prefix}.${index}.js")`)
    .join(",\n");
}

async function removeOldChunks() {
  const filenames = await readdir(OUTPUT_DIR).catch(() => []);
  await Promise.all(
    filenames
      .filter(filename => (
        filename.startsWith(`${MATERIAL_CHUNK_PREFIX}.`) ||
        filename.startsWith(`${GROUP_CHUNK_PREFIX}.`)
      ))
      .map(filename => unlink(join(OUTPUT_DIR, filename)))
  );
}

async function writeChunkFiles(prefix, exportName, chunks) {
  await Promise.all(chunks.map((chunk, index) => {
    const output = `${chunkHeader()}export const ${exportName} = ${stableJson(chunk)};
`;
    return writeFile(join(OUTPUT_DIR, `${prefix}.${index}.js`), output);
  }));
}

async function main() {
  const materials = JSON.parse(await readFile(INPUT_JSON, "utf8"));
  const materialById = new Map();
  const groups = buildMaterialCatalogGroups(materials).map(group => compactGroup(group, materialById));
  const preparedMaterials = [...materialById.values()];
  const sourceCategoryOptions = getMaterialCategoryOptions(materials);
  const groupCategoryCounts = new Map(countOptions(groups, group => group.category).map(option => [option.value, option.count]));
  const categoryOptions = sourceCategoryOptions
    .map(option => ({ ...option, count: groupCategoryCounts.get(option.value) || 0 }))
    .filter(option => option.count > 0);
  const typeOptionsByCategory = buildTypeOptionsByCategory(groups);

  Object.keys(typeOptionsByCategory).forEach(category => {
    typeOptionsByCategory[category] = countOptions(
      groups.filter(group => group.category === category),
      group => group.type
    );
  });

  const sourceTypeOptionCountByCategory = Object.fromEntries(
    sourceCategoryOptions.map(option => [
      option.value,
      getMaterialTypeOptions(materials, option.value).length,
    ])
  );

  const materialChunks = chunkEvenly(preparedMaterials);
  const groupChunks = chunkEvenly(groups);

  const output = `${chunkHeader()}\
export const DENTAL_MATERIAL_CATALOG_SUMMARY = ${stableJson({
    rawItemCount: materials.length,
    preparedMaterialCount: preparedMaterials.length,
    groupCount: groups.length,
    categoryCount: categoryOptions.length,
    sourceTypeOptionCountByCategory,
  })};

export const DENTAL_MATERIAL_CATALOG_CATEGORY_OPTIONS = ${stableJson(categoryOptions)};

export const DENTAL_MATERIAL_CATALOG_TYPE_OPTIONS_BY_CATEGORY = ${stableJson(typeOptionsByCategory)};

const MATERIAL_CHUNK_LOADERS = [
${buildChunkLoaderLines(MATERIAL_CHUNK_PREFIX, materialChunks)}
];

const GROUP_CHUNK_LOADERS = [
${buildChunkLoaderLines(GROUP_CHUNK_PREFIX, groupChunks)}
];

export async function loadDentalMaterialCatalogPreparedData() {
  const [materialModules, groupModules] = await Promise.all([
    Promise.all(MATERIAL_CHUNK_LOADERS.map(loadChunk => loadChunk())),
    Promise.all(GROUP_CHUNK_LOADERS.map(loadChunk => loadChunk())),
  ]);

  return {
    materials: materialModules.flatMap(module => module.DENTAL_MATERIAL_CATALOG_MATERIALS),
    groups: groupModules.flatMap(module => module.DENTAL_MATERIAL_CATALOG_GROUPS),
  };
}
`;

  await mkdir(OUTPUT_DIR, { recursive: true });
  await removeOldChunks();
  await writeFile(OUTPUT_JS, output);
  await writeChunkFiles(MATERIAL_CHUNK_PREFIX, "DENTAL_MATERIAL_CATALOG_MATERIALS", materialChunks);
  await writeChunkFiles(GROUP_CHUNK_PREFIX, "DENTAL_MATERIAL_CATALOG_GROUPS", groupChunks);
  console.log(`Prepared ${materials.length} source materials into ${groups.length} app catalog groups`);
  console.log(OUTPUT_JS);
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
